language: csharp
mono: none
dotnet: 5.0

env:
  global:
    # $ gem install travis
    # If you are using travis-ci.com instead of travis-ci.org, you need to login first: travis login --pro
    # $ travis encrypt NuGetApiKey="deadbeef-3e0e-11eb-81d8-7000c23bcef2" --add
    secure: vC9QTxXicRgN3ij5n5qjq7RntLjQ9dy3JjwYBi/rtcublwnaA2OryLYG+s4sXGSlyk9tBdsWg8kt+VEqiF1cDQy76iYpTSd06CZ/EJqrqrwYTiGHi7kAbZCrRVjwDnYsjHNlzEY9P8Te1YPtdaIabJN7TAQT+amcH047nw9eNZEQWhrsso7quE+C2GAJaz3ANtdpcdHGIdfrEJ636hRRVd3H9ZYnVUO8eqXds6v6t/jhCvLBRbB/bFSk0RRC50JwUJpBdM14pH16pYfSZwKV+rtodUnSzga5LY+dFUoQj2ymDMkNiaOAopNy0OB+E45BXNGPBahBihkRlgs87KazVkWbdsM6ctBqBF97tiwA8joo/0mSJuzBwYEQLLxXx5n8BHzUpBhU+h3R2BWm1WsOD786/j4Cj92w30bpj6RpDyVRaNPL69hJRSD+7+2j/N/FoJHrUFNe20b+BYr5dwCFMHPO4INGjqQsP7zUmPtpAAMNeINJ4zh3Ee62j2siI6Vz7ZJL24su4VrHXb5hZWqwMF0RNgDvOzB0P5ZuI9usv6Le/EydJkhr+zH9kBlSPsxujWcpt6+OaUPm8DIO89hzA48As+jJf4tBmrgwuNLb7av/ZuxI9Hp7ifQzArWB3yFkIW25mwthX6hysV1k9ch9yirmHDtkdUj/qE2yl9DUcwk=

script:
  - dotnet test
  - dotnet build

deploy:
  provider: script
  edge: true
  script: dotnet msbuild -t:Deploy
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH == "main" || -n $TRAVIS_TAG
