language: csharp
mono: none
dotnet: 5.0

script:
  - dotnet test
  - dotnet build

deploy:
  provider: script
  edge: true
  script: dotnet msbuild -t:PushPackages
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH == "main" || -n $TRAVIS_TAG
